# Podfile
use_frameworks!

target 'RangeMeter' do
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod 'Moya/RxSwift', '~> 10.0'
    pod 'SnapKit', '~> 4.0.0'
    pod 'ObjectMapper', '~> 3.1'
    pod 'RxAlamofire'
    pod 'Alamofire', '~> 4.7'
end
